services:
  server:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - .:/app/
    links:
      - php
    networks:
      - pg-network

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - pg-network
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./docker/db:/docker-entrypoint-initdb.d

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app
    networks:
      - pg-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - pg-network

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "${MAILPIT_PORT:-8025}:8025"
    networks:
      - pg-network

  pgadmin-wdpai:
    image: dpage/pgadmin4:latest
    container_name: ${PGADMIN_CONTAINER_NAME:-pg-admin}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - pg-network

networks:
  pg-network:

volumes:
  pg-data:
  ollama_data:
